// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackingSystem.App.Data;

#nullable disable

namespace TrackingSystem.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackingSystem.App.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("LocalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePriceUSD")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("WarrantyExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Dell",
                            EmployeeId = 1,
                            LocalPrice = 15750.00m,
                            ModelName = "XPS 15",
                            OfficeId = 1,
                            PurchaseDate = new DateTime(2023, 6, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5203),
                            PurchasePriceUSD = 1500.00m,
                            SerialNumber = "DELL-XPS-001",
                            Type = 1,
                            WarrantyExpirationDate = new DateTime(2025, 6, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5302)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Apple",
                            EmployeeId = 2,
                            LocalPrice = 25200.00m,
                            ModelName = "MacBook Pro 14",
                            OfficeId = 1,
                            PurchaseDate = new DateTime(2023, 9, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5311),
                            PurchasePriceUSD = 2400.00m,
                            SerialNumber = "APPLE-MBP-001",
                            Type = 1,
                            WarrantyExpirationDate = new DateTime(2026, 9, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5317)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "HP",
                            LocalPrice = 12600.00m,
                            ModelName = "EliteDesk 800",
                            OfficeId = 1,
                            PurchaseDate = new DateTime(2025, 5, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5323),
                            PurchasePriceUSD = 1200.00m,
                            SerialNumber = "HP-ED-001",
                            Type = 2,
                            WarrantyExpirationDate = new DateTime(2028, 5, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5328)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Apple",
                            EmployeeId = 3,
                            LocalPrice = 869.00m,
                            ModelName = "iPhone 15 Pro",
                            OfficeId = 2,
                            PurchaseDate = new DateTime(2025, 11, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5333),
                            PurchasePriceUSD = 1100.00m,
                            SerialNumber = "APPLE-IP15-001",
                            Type = 3,
                            WarrantyExpirationDate = new DateTime(2027, 11, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5337)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Lenovo",
                            EmployeeId = 4,
                            LocalPrice = 1422.00m,
                            ModelName = "ThinkPad X1 Carbon",
                            OfficeId = 2,
                            PurchaseDate = new DateTime(2023, 7, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5342),
                            PurchasePriceUSD = 1800.00m,
                            SerialNumber = "LEN-X1C-001",
                            Type = 1,
                            WarrantyExpirationDate = new DateTime(2025, 7, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5346)
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Apple",
                            LocalPrice = 1012.00m,
                            ModelName = "iPad Pro 12.9",
                            OfficeId = 3,
                            PurchaseDate = new DateTime(2024, 11, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5351),
                            PurchasePriceUSD = 1100.00m,
                            SerialNumber = "APPLE-IPAD-001",
                            Type = 4,
                            WarrantyExpirationDate = new DateTime(2026, 11, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5356)
                        },
                        new
                        {
                            Id = 7,
                            Brand = "HP",
                            LocalPrice = 414.00m,
                            ModelName = "LaserJet Pro M428",
                            OfficeId = 3,
                            PurchaseDate = new DateTime(2023, 11, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5361),
                            PurchasePriceUSD = 450.00m,
                            SerialNumber = "HP-PRINT-001",
                            Type = 5,
                            WarrantyExpirationDate = new DateTime(2025, 11, 22, 10, 20, 33, 485, DateTimeKind.Local).AddTicks(5365)
                        });
                });

            modelBuilder.Entity("TrackingSystem.App.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT",
                            Email = "anna.andersson@company.com",
                            FullName = "Anna Andersson"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Finance",
                            Email = "erik.eriksson@company.com",
                            FullName = "Erik Eriksson"
                        },
                        new
                        {
                            Id = 3,
                            Department = "HR",
                            Email = "maria.garcia@company.com",
                            FullName = "Maria Garcia"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Sales",
                            Email = "john.smith@company.com",
                            FullName = "John Smith"
                        });
                });

            modelBuilder.Entity("TrackingSystem.App.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("TrackingSystem.App.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Stockholm",
                            Country = "Sweden",
                            CurrencyCode = "SEK",
                            ExchangeRate = 10.5m,
                            Name = "Stockholm HQ"
                        },
                        new
                        {
                            Id = 2,
                            City = "London",
                            Country = "UK",
                            CurrencyCode = "GBP",
                            ExchangeRate = 0.79m,
                            Name = "London Office"
                        },
                        new
                        {
                            Id = 3,
                            City = "Madrid",
                            Country = "Spain",
                            CurrencyCode = "EUR",
                            ExchangeRate = 0.92m,
                            Name = "Madrid Office"
                        });
                });

            modelBuilder.Entity("TrackingSystem.App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 1,
                            Password = "manager123",
                            Role = 2,
                            Username = "manager"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 2,
                            Password = "employee123",
                            Role = 3,
                            Username = "employee"
                        });
                });

            modelBuilder.Entity("TrackingSystem.App.Models.Asset", b =>
                {
                    b.HasOne("TrackingSystem.App.Models.Employee", "Employee")
                        .WithMany("AssignedAssets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrackingSystem.App.Models.Office", "Office")
                        .WithMany("Assets")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("TrackingSystem.App.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("TrackingSystem.App.Models.Asset", "Asset")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TrackingSystem.App.Models.User", b =>
                {
                    b.HasOne("TrackingSystem.App.Models.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("TrackingSystem.App.Models.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TrackingSystem.App.Models.Asset", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("TrackingSystem.App.Models.Employee", b =>
                {
                    b.Navigation("AssignedAssets");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackingSystem.App.Models.Office", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
